import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-web.golfsafaris.click/#/sign-in?redirectURL=%2Fdashboard');
  await page.getByLabel('Email / Username *').click();
  await page.getByPlaceholder('Enter your email / username...').fill('admin');
  await page.getByPlaceholder('Enter your email / username...').press('Tab');
  await page.getByPlaceholder('Enter your password...').fill('password123!');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('app-itinerary-search').getByRole('button').click();
  await page.getByPlaceholder('Search for a reservation').fill('67676');
  await page.getByText('67676 May 23, 2024 - May 26,').click();
  await page.getByRole('heading', { name: 'Thu, May 23, 2024 Sun, May 26' }).getByLabel('loading').click();
  await page.locator('button',{class: 'mat-focus-indicator mat-tooltip-trigger side-nav__toggle mat-icon-button mat-button-base ng-tns-c188-101 ng-star-inserted'}).click();
  await page.getByText('CA$17,444.66').click();
  await page.locator('ui-alert div').filter({ hasText: 'Price splitting is enabled' }).first().click();
  await page.locator('ui-page-header').getByText('Osoyoos').click();
  await page.getByText('BC Golf Safaris').click();
  const page1Promise = page.waitForEvent('popup');
  //await page.getByRole('link', { name: 'Coast Osoyoos Beach Hotel' }).nth(2).click();
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  //await page.locator('ui-table-row').filter({ hasText: '8 Best Western Plus Osoyoos' }).getByRole('link').click();
  const page2 = await page2Promise;
  await page.locator('ui-page-header').getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Clone Reservation' }).click();
  await page.locator('#mat-input-5').click();
  await page.getByLabel('Choose month and year').click();
  await page.getByLabel('2025').click();
  await page.getByLabel('January').click();
  await page.getByLabel('January 23,').click();
  await page.locator('#mat-dialog-0 ui-chip').getByRole('button').click();
  await page.locator('app-customer-select').getByRole('button').click();
  await page.getByRole('textbox', { name: 'Search for an existing' }).click();
  await page.getByRole('textbox', { name: 'Search for an existing' }).fill('neetha.john');
  await page.getByRole('textbox', { name: 'Search for an existing' }).press('Enter');
  await page.getByText('neetha.john@aot-technologies.com 9022008815').click();
  await page.getByRole('button', { name: 'Select Customer' }).click();
  await page.getByRole('button', { name: 'Clone Reservation' }).click();
  await page.getByText('CA$4,216.86').click();
  await expect(page.getByText('CA$4,216.86')).toBeVisible();
  await expect(page.locator('ui-page-header').getByText('Osoyoos')).toBeVisible();
  await expect(page.getByText('BC Golf Safaris')).toBeVisible();
  await page.getByText('Overview').click();
  await expect(page.getByRole('link', { name: 'neetha.john@aot-technologies.' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Coast Osoyoos Beach Hotel' }).nth(2)).toBeVisible();
  await expect(page.locator('ui-table-row').filter({ hasText: '8 Best Western Plus Osoyoos' }).getByRole('link')).toBeVisible();
  await expect(page.getByText('Price splitting is enabled for this reservation, so per person pricing is')).toBeVisible();
  await page.getByText('Pricing', { exact: true }).click();
  await expect(page.getByText('Price Splitting is Enabled', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Price Overrides' })).toBeVisible();
  await expect(page.locator('app-reservation-price-overrides').getByRole('link', { name: 'Fairview Mountain Golf Club' })).toBeVisible();
});